feign:
  url:
    prefix: http://localhost:8080/target-server
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: NONE
      demo-client: # DemoFeignClient? ??? ??.
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: HEADERS # ? ?? FeignCustomLogger -> Logger.Level logLevel  ? ???.
